import type { Config } from 'tailwindcss';

export default {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './index.html'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        jakarta: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display': ['48px', { lineHeight: '1.1', fontWeight: '800', letterSpacing: '-0.02em' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '1', fontWeight: '700', letterSpacing: '0.05em' }],
        'label-md': ['14px', { lineHeight: '1', fontWeight: '500' }],
      },
      spacing: {
        'unit': '8px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'gutter': '24px',
        'container-padding': '32px',
        'touch-target-min': '48px',
      },
      borderRadius: {
        'control': '8px',
        'card': '24px',
        'pill': '9999px',
      },
      boxShadow: {
        'control': '0 4px 20px rgba(0, 0, 0, 0.5)',
        'panel': '0 8px 30px rgba(225, 29, 72, 0.3)',
      },
      colors: {
        'surface-bright': '#31394d',
        'surface-container': '#1d2539',
        'surface-container-low': '#131b2e',
        'surface-container-high': '#222a3d',
        'surface-container-lowest': '#060e20',
        'surface-container-highest': '#2d3449',
        'surface-variant': '#2d3449',
        'surface-dim': '#0b1326',
        'surface-tint': '#be0037',
        'on-surface-variant': '#d9e3f6',
        'on-secondary-fixed': '#0d1c2f',
        'on-secondary-fixed-variant': '#3a485c',
        'on-secondary-container': '#abb9d2',
        'secondary-container': '#3c4a5e',
        'secondary-fixed': '#d5e3fd',
        'secondary-fixed-dim': '#b9c7e0',
        'inverse-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
        'inverse-primary': '#be0037',
        'on-primary': '#68001a',
        'on-primary-container': '#fffaf9',
        'on-primary-fixed': '#40000c',
        'on-primary-fixed-variant': '#920028',
        'primary-container': '#e11d48',
        'primary-fixed': '#ffdada',
        'primary-fixed-dim': '#ffb3b6',
        'tertiary': '#c4c7c9',
        'on-tertiary': '#2d3133',
        'on-tertiary-fixed': '#191c1e',
        'on-tertiary-fixed-variant': '#444749',
        'tertiary-fixed': '#e0e3e5',
        'tertiary-fixed-dim': '#c4c7c9',
        'tertiary-container': '#717476',
        'on-tertiary-container': '#f9fbfd',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'error-container': '#93000a',
        'outline': '#ac8889',
        'outline-variant': '#5c3f40',
      },
    },
  },
  plugins: [],
} satisfies Config;
